### ISSUE TITLE
Stabilize: load-from-file

### ISSUE THREAD

**Issue by jcornaz** [jcornaz/benimator#62]
The cargo feature `unstable-load-from-file` allows loading animation from YAML or RON files.

Eventually, this should be stabilized. The present issue is there to track what needs to be considered/done before stabilizing the feature.

It is also open to gathering comments and thoughts about the current state of the API.

## Tasks
* [x] fix crash when one frame duration is zero
* [x] make it easier to write an animation file when all frames have the same duration
* [x] configure documentation so that the new API shows up on docs.rs
* [x] ron support
* [x] gate yaml and ron behind feature flags (in addition of the `load-from-file` gate)
* [x] document shorthand notation for ron
* [x] implicit_some for ron
* [x] remove public functions `from_(yaml|ron)_(str|bytes)`.
  * Having a public implementation or `serde::Deserialize` is enough to let the user choose the format and library of their choice. Not to mention that most users would not use it directly anyway as they would use the asset loader instead.

## Open questions
* [x] is yaml a good choice?
  * [I think it is](https://github.com/jcornaz/benimator/issues/62#issuecomment-1160828488). However, I am okay to support additional formats (such as ron) and let the user choose what they prefer.
* [x] is the extension `.animation.(yaml|yml|ron)` a good choice?
  * I think it is not bad. Ultimately if it turns out to be problematic later, it would be possible to let the user choose the extension (without breaking the API)
* [x] is the schema sensible? Clearly understood/documented?
  * I think it is not too bad. Not to say it is perfect, but I think it doesn't block the stabilization of the feature. We may still improve it later without breaking the API.

**Comment by flipbit03** [comment]
I'd argue that [ron](https://github.com/ron-rs/ron) (Rusty Object Notation) is a (subjectively) better, prettier choice!

**Comment by jcornaz** [comment]
@flipbit03 I just added `ron` support, so we can try it out to see if it would be a good fit.

But to be honest, In my own opinion, I think YAML is clearly superior, at least in this context.

Here is a quick comparison: 

# Simple animation

## yaml
3 lines, no commas
```yaml
mode: Repeat
frame_duration: 100
frames: [0, 1, 2, 3, 4]
```

## ron
5 lines, commas, more indentation and `Some`
```ron
(
  mode: Repeat,
  frame_duration: Some(100),
  frames: [0, 1, 2, 3, 4],
)
```

# More complex animation

## yaml
8 lines, no commas
```yaml
mode:
  RepeatFrom: 1
frame_duration: 80
frames:
     - index: 0
     - index: 1
     - index: 2
       duration: 120
```

## ron
18 lines, commas, a lot more indentation, `None` and `Some`
```ron
(
  mode: RepeatFrom(1),
  frame_duration: Some(80),
  frames: [
     (
        index: 0,
        duration: None,
     ),
     (
       index: 1,
       duration: None,
     ),
     (
       index: 2,
       duration: Some(120),
     ),
  ],
)
```


I am of course open to suggestion on how the `ron` format could be improved.

**Comment by flipbit03** [comment]
I kinda of agree with your point. Although I don't think having both can hurt and that could enable more diversity. That is, unless the cost of implementing or maintaining this extra format becomes a hurdle.

By the way, the "implicit_some" feature of Ron can make those Some()'s go away.

Have a good one, and thank you for the reply/post/comparisons!
